name: binance
description: A wrapper for Binance API with serialized data classes, futures, and streams.
version: 1.0.0
author: Luke Pighetti<lukepighetti@gmail.com>
homepage: http://github.com/lukepighetti/binance-dart

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  http: ^0.12.0
  web_socket_channel: ^1.0.9

dev_dependencies:
  test: ^1.5.1+1